from . import hostel_property
from . import hostel_amenity
from . import hostel_document_type
from . import hostel_bed_type
from . import hostel_sleeping_type
from . import hostel_cancellation_policy
from . import hostel_booking_source
from . import hostel_charge_type
from . import hostel_housekeeping_task_type
from . import hostel_room_type
from . import hostel_rate_plan
from . import hostel_room
from . import hostel_bed
from . import hostel_housekeeping_task
from . import res_partner
from . import res_users
from . import hostel_booking
from . import hostel_folio
from . import hostel_folio_line
from . import account_move
